version: '3.9'

services:
  web:
    build: .
    command: gunicorn linked_ai.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - ollama

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: linked_ai_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    # Optionally, preload the llama3 model
    command: [ "ollama", "serve" ]

volumes:
  postgres_data:
  ollama_data:
