# Generated by Django 5.1.7 on 2025-03-24 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.CharField(help_text='E.g., AI, web development, cybersecurity', max_length=200)),
                ('fields', models.CharField(help_text='E.g., software engineering, data science', max_length=200)),
                ('experience', models.CharField(choices=[('entry-level', 'Entry Level'), ('junior', 'Junior'), ('mid-level', 'Mid-Level'), ('senior', 'Senior'), ('lead', 'Lead/Principal')], max_length=100)),
                ('job_preferences', models.CharField(help_text='E.g., remote, full-time, startup', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
