# Generated by Django 5.1.7 on 2025-04-02 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joblisting',
            options={'ordering': ['-posted_at']},
        ),
        migrations.AddField(
            model_name='joblisting',
            name='experience',
            field=models.CharField(blank=True, choices=[('entry-level', 'Entry Level'), ('junior', 'Junior'), ('mid-level', 'Mid-Level'), ('senior', 'Senior'), ('lead', 'Lead/Principal')], max_length=100),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='fields',
            field=models.CharField(blank=True, help_text='Relevant fields', max_length=200),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='interests',
            field=models.CharField(blank=True, help_text='Required skills or interests', max_length=200),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='job_preferences',
            field=models.CharField(blank=True, help_text='Job type preferences (e.g., remote, full-time)', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'Job Seeker'), ('employer', 'Employer'), ('admin', 'Admin')], default='user', max_length=10),
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_website', models.URLField(blank=True)),
                ('company_description', models.TextField()),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('company_size', models.CharField(choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('501-1000', '501-1000 employees'), ('1001+', '1001+ employees')], max_length=50)),
                ('industry', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to='core.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='joblisting',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_listings', to='core.employerprofile'),
        ),
    ]
