# Generated by Django 5.1.7 on 2025-04-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_joblisting_options_joblisting_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='experience',
            field=models.CharField(blank=True, choices=[('entry-level', 'Entry Level'), ('junior', 'Junior'), ('mid-level', 'Mid-Level'), ('senior', 'Senior'), ('lead', 'Lead/Principal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fields',
            field=models.CharField(blank=True, help_text='E.g., software engineering, data science', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.CharField(blank=True, help_text='E.g., AI, web development, cybersecurity', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='job_preferences',
            field=models.CharField(blank=True, help_text='E.g., remote, full-time, startup', max_length=200),
        ),
    ]
